### ISSUE TITLE
Flathub faulty and wrong links

### ISSUE THREAD

**Issue by EchedeyLR** [flathub/com.yubico.yubioath#1]
The website link is pointing to the "Issues" manager (to create a new ticket to be exact) and seems that any other link was added.

Check at the bottom of the following image to see the preview link in which the button will redirect an user.
![Captura de pantalla de 2020-04-27 20-24-58](https://user-images.githubusercontent.com/56733813/80412253-80db1e00-88c5-11ea-8145-af2cfdbca601.png)

**Comment by bilelmoussaoui** [comment]
This comes from the upstream metainfo file https://github.com/Yubico/yubioath-desktop/blob/master/resources/com.yubico.yubioath.appdata.xml#L11 and should be fixed there.

**Comment by EchedeyLR** [comment]
@bilelmoussaoui so known issue and not reported or notified by yourself?

**Comment by EchedeyLR** [comment]
Thank you anyways. I will point the issue there.

**Comment by bilelmoussaoui** [comment]
> @bilelmoussaoui so known issue and not reported or notified by yourself?

No idea. I don't maintain this package, I just mentioned where you should report/fix the issue :)

**Comment by ai** [comment]
@EchedeyLR for some reason upstream author decided to use this URL.

In my PR it was another URL. Can you send PR to upstream to show that multiple people want to change it
https://github.com/Yubico/yubioath-desktop/blob/master/resources/com.yubico.yubioath.appdata.xml#L11

If they will refuse it, we can try to fix it in the patch. But I hope we will not need to do it.

**Comment by EchedeyLR** [comment]
> > @bilelmoussaoui so known issue and not reported or notified by yourself?
> 
> No idea. I don't maintain this package, I just mentioned where you should report/fix the issue :)

Maybe I was a bit rude with my message (and I'm sorry about it). I didn't take so kind your message pointing me there instead of helping me a bit with the report there. But anyways, thank you at least for pointing me.

**Comment by EchedeyLR** [comment]
> @EchedeyLR for some reason upstream author decided to use this URL.
> 
> In my PR it was another URL. Can you send PR to upstream to show that multiple people want to change it
> https://github.com/Yubico/yubioath-desktop/blob/master/resources/com.yubico.yubioath.appdata.xml#L11
> 
> If they will refuse it, we can try to fix it in the patch. But I hope we will not need to do it.

I am not sure if I understood you with your PR. You want I send a PR to upstream with your changes to see?

**Comment by ai** [comment]
@EchedeyLR issue you already created is enough

**Comment by EchedeyLR** [comment]
> @EchedeyLR issue you already created is enough

Oh, okay. I'm sorry for not understanding so much. The only think I could help would be checking other metadata files to, at least, put the correct website and add a issue link. Not idea away from that as I knew the software just moments ago.
