### ISSUE TITLE
Can't see smart card on Fedora 33 or RHEL 8

### ISSUE THREAD

**Issue by tkuraku** [flathub/com.yubico.yubioath#12]
I have installed the  PCSC daemon and am able to see the yubikey with the command pcsc_scan, but I cannot see it with the flatpaked application on Fedora 33 or RHEL 8. Is there some setup that I am missing?

**Comment by ai** [comment]
Do you use NFC reader? You need to change Interface in Settings.

**Comment by tkuraku** [comment]
No, This is with USB.

**Comment by tkuraku** [comment]
It works fine with the appimage.

https://bugzilla.redhat.com/show_bug.cgi?id=1906652

**Comment by ai** [comment]
Strange. It works with YubiKey on my laptop and Fedora 33 perfectly fine.

Did you installed `pcsc-lite`? What is `systemctl status pcscd.service` output?

**Comment by tkuraku** [comment]
yes I have `pcsc-lit` installed. I checked it and it is running, but on closer inspection it failes to open the Yubikey. I assumed it would be fine since the appimage version can read the yubikey just fine.

```
$ sudo systemctl status pcscd
● pcscd.service - PC/SC Smart Card Daemon
   Loaded: loaded (/usr/lib/systemd/system/pcscd.service; indirect; vendor preset: disabled)
   Active: active (running) since Fri 2021-04-16 19:08:25 PDT; 3s ago
 Main PID: 79332 (pcscd)
    Tasks: 5 (limit: 150548)
   Memory: 2.1M
   CGroup: /system.slice/pcscd.service
           └─79332 /usr/sbin/pcscd --foreground --auto-exit

Apr 16 19:08:25 tc-desktop systemd[1]: Started PC/SC Smart Card Daemon.
Apr 16 19:08:25 tc-desktop pcscd[79332]: 00000000 ifdhandler.c:150:CreateChannelByNameOrChannel() failed
Apr 16 19:08:25 tc-desktop pcscd[79332]: 00000045 readerfactory.c:1106:RFInitializeReader() Open Port 0x200000 Failed (usb:1050/0406:libudev:0:/dev/bus/usb/003/007)
Apr 16 19:08:25 tc-desktop pcscd[79332]: 00000002 readerfactory.c:376:RFAddReader() Yubico Yubikey 4 U2F+CCID init failed.
```
Any suggestions? 

I suppose this is not a bug report for here now and can be closed.

**Comment by ai** [comment]
Sorry. Have no idea.

**Comment by tkuraku** [comment]
Just as a note, sometime recently there was an update and now it can see the smart card as expected!
