### ISSUE TITLE
error installing program, latest flatpak version needed.

### ISSUE THREAD

**Issue by VaGNaroK** [flathub/com.yubico.yubioath#2]
after trying to install the application on linux mint 19.3, a message appears saying that the version of flatpak (1.3.2) is needed and the installation ends.

screen:
https://postimg.cc/r0dW9Sb3

**Comment by ai** [comment]
https://github.com/flathub/com.yubico.yubioath/blob/master/com.yubico.yubioath.json#L17

Yeap. This application needs very specific Flatpak feature (pcsc), which was added only in the latest release.

I do not know how to fix it. If you will know, I add be glad to recieve PR.

**Comment by VaGNaroK** [comment]
I understand, hmm ... so I will have to update my version of flatpak to use this program. Well, at least just updating is enough.
