### ISSUE TITLE
System theme

### ISSUE THREAD

**Issue by ai** [flathub/com.yubico.yubioath#21]
Flathub version of Yubico Authenticator doesn’t see system dark/light theme changes.

1. Settings → Appearance: System default
2. Enable dark mode (set `Adwaita-dark` theme for GNOME)
3. Run Yubico Authenticator
4. We have light theme, not dark (both app and window decoration are light).

Why it is important: schedule-based theme changes are popular.

@Lunarequest any idea how to fix it? Maybe we need to add permission to check system theme?

**Comment by Lunarequest** [comment]
Yubioath is a qt based app last I checked gnome doesn't theme qt apps

**Comment by Lunarequest** [comment]
@ai try installing the following flatpaks org.kde.KStyle.Adwaita and org.kde.PlatformTheme.QGnomePlatform. It should make everything automatically theme. I can confirm that on KDE plasma yubioath picks up breeze dark on its own

**Comment by Lunarequest** [comment]
Just change the runtime version and rebuild it how you normally do

**Comment by ai** [comment]
On previous version of 5.15 it was the same issue.

Is it OK to use PRs to re-build packages?

**Comment by ai** [comment]
It fixed. Thanks. PR https://github.com/flathub/com.yubico.yubioath/pull/22

**Comment by Lunarequest** [comment]
The required packages are now up to date I am closing this issue
