### ISSUE TITLE
YubiKey detected but no credentials

### ISSUE THREAD

**Issue by Erick555** [flathub/com.yubico.yubioath#6]
App successfully detects my YubiKey but doesn't show any credentials stored. It neither works for 5.0.4 or 5.0.3 version when I downgrade. It works outside flatpak. My distro is Arch Linux.

**Comment by ai** [comment]
PR is welcome. Sorry, I am new with Linux development.

For me, both flatpak and rpm versions sometime do not show codes from the key. Pulling out and puting key in again solves the problem.

**Comment by Erick555** [comment]
Pulling key out doesn't help for me.

**Comment by ai** [comment]
@Erick555 do you have `pcsc-lite` daemon installed on your machine?

**Comment by Erick555** [comment]
Yes, as I wrote it works with distro package and even in flatpak the key itself is detected. Only credentials aren't shown.

**Comment by Erick555** [comment]
Flatpak app also works for me on ubuntu 20.04 so there is something special happening on Arch Linux.

**Comment by Erick555** [comment]
Actually everything works fine. The problem was that when app window is too narrow then it's completely blank but when I make it just slightly bigger than all credentials show up magically.
