### ISSUE TITLE
New stable release.

### ISSUE THREAD

**Issue by Eric1212** [flathub/com.yubico.yubioath#60]
Hello there, a new stable release is available.

https://developers.yubico.com/yubioath-flutter/Releases/

It's might also be a good idea to come back in a few weeks to see if they fix somes bugs and release a 6.0.1 or something.

Thanks. :)

**Comment by brugr** [comment]
im currently trying to fix a pull req for it :)
should hopefully be up later today

**Comment by Eric1212** [comment]
Apparently, we will be able to import directly from google authenticator QR code in v6 !!

**Comment by brugr** [comment]
opened a pr #61

**Comment by Lunarequest** [comment]
closing since pr has been merged
