### ISSUE TITLE
Would it be possible to extend support to Fedora?

### ISSUE THREAD

**Issue by jonasbb** [flathub/com.yubico.yubioath#65]
Fedora 38 will stop shipping yubioath-desktop ([Source](https://discussion.fedoraproject.org/t/f38-yubioath-desktop-will-no-longer-be-available-in-fedora-repository/45921)). This means in the next version there is GUI to manage TOTP.
Sadly, this flatpak does not work as a replacement, since the code crashes and cannot get a pcscd connection. The Readme mentions that:
> NOTE: This (community) flatpak currently has issues with distros that use a patched version of pcsc-lite, like Fedora. DON'T report this to Yubico.

Upstream stopped supporting appimages since the transition to the flutter UI: https://github.com/Yubico/yubioath-flutter/issues/854
The only option left is downloading the `yubico-authenticator-6.1.0-linux.tar.gz` from the Yubico website, which is quite a suboptimal experience (no proper installs, manual updates).

So would it be possible to extend the support of this flatpak to Fedora, to avoid these shortcomings?

**Comment by Erick555** [comment]
Only fedora could fix this and [it seems they did](https://src.fedoraproject.org/rpms/pcsc-lite/c/330bcc20f39656815bf597bf4b305ad3462f9205?branch=rawhide) in rawhide branch (F37 won't work). Did you test it with rawhide?

**Comment by jonasbb** [comment]
I didn't know that this is a Fedora bug, but good to know that this is going to get fixed with the next release. I don't have a rawhide installation at hand right now. But I installed `pcsc-lite` and `pcsc-lite-libs` from F38 and with that the flatpak starts and I can access my TOTPs. Running a different `pcsc-lite` is good enough for me right now. Thanks for the help and information :)
