### ISSUE TITLE
Flatpak missing dependency

### ISSUE THREAD

**Issue by andmalc** [flathub/com.yubico.yubioath#7]
- Yubico Authenticator version: 5.0.4 installed from Flatpak
- Operating system and version:  Fedora Workstation 32 and Silverblue 32
- YubiKey model and version: 5 NFC
- Bug description summary: Key not detected without pcsc-lite installed 

Steps to reproduce

Installed Yubico Authenticator from flatpak here: https://flathub.org/apps/details/com.yubico.yubioath
Ran app - console output includes `failed to update readers: no_pcscd`
Inserted Yubikey in USB port: Key is not shown 

Installed pcsc_lite package using dnf on Fedora Workstation and rpm-ostree on Silverblue
Ran app and inserted key: 
Key is detected and shows saved TOTP codes.

**Comment by bilelmoussaoui** [comment]
No, the flatpak uses pscs socket https://github.com/flathub/com.yubico.yubioath/blob/master/com.yubico.yubioath.json#L18 to communicate with the host and uses smart card devices (in your case, the Yubico Key). If the host doesn't provide that, there's nothing to be done from the app side really.

I would suggest opening an issue asking to have whatever provides that socket pre-installed on Fedora Silverblue

**Comment by andmalc** [comment]
Thanks for the clarification - I hadn't understood that the Flatpak can't communicate with hardware directly.  

FWI pcsc-lite will be installed by default in the next version of Fedora Workstation and Silverblue.
