### ISSUE TITLE
libnotify.so.4 not found

### ISSUE THREAD

**Issue by pushrbx** [flathub/com.yubico.yubioath#70]
I tried to install the latest version recently, and I've received the following error:

```
$ flatpak run com.yubico.yubioath
authenticator: error while loading shared libraries: libnotify.so.4: cannot open shared object file: No such file or directory
```

My system setup:
![image](https://user-images.githubusercontent.com/6832715/233296663-908aae83-95d0-427c-b3f4-042d8d6d1c33.png)

app version: `6.2.0`

**Comment by Erick555** [comment]
This was already fixed https://github.com/flathub/com.yubico.yubioath/pull/69
You need do `flatpak update`.

**Comment by pushrbx** [comment]
Thanks, running `flatpak update` again solved the issue. I had bad internet connection all day yesterday probably that caused something when I installed the package. This can be considered done.
