### ISSUE TITLE
[aarch64] '/app/bin/authenticator: cannot execute binary file'

### ISSUE THREAD

**Issue by maxrdz** [flathub/com.yubico.yubioath#81]
Getting the following when running yubico authenticator.
```
/app/bin/authenticator: /app/bin/authenticator: cannot execute binary file
```
My first thought was that this is an x86_64 binary, but I see that the flatpak is available for aarch64 systems. Is this a bug or an error in the architecture options?

**Comment by Erick555** [comment]
flatpak uses upstream binaries which aren't published for aarch64 architecture which effectively means x86_64 binary is packaged into aarch64 flatpak which obviously can't work. This was missed while updating to flutter based yubioath - previous version was build from sources for aarch64 as well.
